# Generated by Django 4.2 on 2023-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='icono',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
