# Generated by Django 4.2 on 2023-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_links_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='icono',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
