# Generated by Django 4.2 on 2023-05-19 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
