# Generated by Django 4.2 on 2023-05-19 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_links_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='autor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='categorias',
            field=models.ManyToManyField(related_name='get_posts', to='core.category'),
        ),
    ]
