# Generated by Django 4.2 on 2023-05-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_links_autor_links_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='autor',
        ),
    ]
