# Generated by Django 4.2 on 2023-05-19 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_links_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
