# Generated by Django 4.2 on 2023-05-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_links_publicado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='categoria',
        ),
    ]
