# Generated by Django 4.2.4 on 2023-08-19 14:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_category_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=70)),
                ("contenido", ckeditor.fields.RichTextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "valor",
                "verbose_name_plural": "valores",
                "ordering": ["-creado"],
            },
        ),
    ]
