# Generated by Django 4.2 on 2023-08-23 22:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="empress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=70)),
                ("contenido", ckeditor.fields.RichTextField()),
                (
                    "image",
                    models.ImageField(upload_to="empresas", verbose_name="Imagen"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "valor",
                "verbose_name_plural": "valores",
                "ordering": ["-creado"],
            },
        ),
        migrations.DeleteModel(name="empresa",),
    ]
