# Generated by Django 4.2 on 2023-08-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_empress_delete_empresa"),
    ]

    operations = [
        migrations.DeleteModel(name="empress",),
    ]
