# Generated by Django 4.2 on 2023-09-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0003_rename_portafolio_project"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="categories",),
        migrations.DeleteModel(name="category",),
        migrations.DeleteModel(name="project",),
    ]
