# Generated by Django 4.2 on 2023-08-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="address",),
        migrations.RemoveField(model_name="profile", name="image",),
        migrations.RemoveField(model_name="profile", name="location",),
        migrations.RemoveField(model_name="profile", name="telephone",),
    ]
