# Generated by Django 4.2.1 on 2023-08-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_project_options_project_link_project_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-creado'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
