# Generated by Django 4.2 on 2023-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_project_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de edicion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Nombre")),
                ("descripcion", models.TextField(verbose_name="Descripcion")),
                (
                    "image",
                    models.ImageField(upload_to="projects", verbose_name="Imagen"),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("price", models.FloatField(max_length=20, verbose_name="Precio")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de edicion"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        max_length=20, to="productos.category", verbose_name="categoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-created"],
            },
        ),
        migrations.DeleteModel(name="project",),
    ]
